# en_localization.py
PROMPT_ENTER_FIRST_NUMBER = "Enter the first number: "
PROMPT_ENTER_SECOND_NUMBER = "Enter the second number: "
INVALID_INPUT = "Invalid input. Please enter a valid number."
PROMPT_CHOOSE_OPERATOR = "Choose operator (+, -, *, /, ^, √, %): "
INVALID_OPERATOR = "Invalid operator. Please enter a valid operator from the list (+, -, *, /, ^, √, %): "
PROMPT_ENTER_DECIMAL_PLACES = "Enter the number of decimal places: "
RESULT_FORMAT = "Result: {result:.{decimal_places}f}"
MEMORY_OPERATOR_HEADER = "Memory operator:"
CONTINUE_CALCULATION_PROMPT = "Do you want to perform another calculation? (yes/no): "
CONTINUE_CALCULATION = "yes"
BAN_FOR_ZERO = "Error: Division by zero is not allowed"